pipeline {
    agent any
    
    tools {
        maven 'Maven3'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('database-stats-agent') {
                    sh 'docker build -t app-image:${BUILD_NUMBER} .'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''
                    docker stop app-container || true
                    docker rm app-container || true
                    docker run -d \
                        --rm \
                        --name app-container \
                        --network host \  # 添加这行使用主机网络
                        -p 8081:8081 \
                        -v ${WORKSPACE}/logs:/app/logs \
                        -e SPRING_DATA_MONGODB_URI=mongodb://localhost:27017 \
                        app-image:${BUILD_NUMBER}
                '''
            }
        }
    }
    
    post {
        success {
            echo '部署成功'
        }
        failure {
            echo '部署失败'
        }
    }
}